In [ ]:
## Classification Algorithms
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

import pandas as pd
import numpy as np
# For K-Means Clustering
from sklearn.cluster import KMeans
# For Silhouette Analysis


# For PCA
from sklearn.decomposition import PCA 

# importing ploting libraries
import matplotlib.pyplot as plt   

#importing seaborn for statistical plots
import seaborn as sns

#Let us break the X and y dataframes into training set and test set. For this we will use
#Sklearn package's data splitting function which is based on random function

from sklearn.cross_validation import train_test_split
from scipy.stats import zscore



# calculate accuracy measures and confusion matrix
from sklearn import metrics
# To enable plotting graphs in Jupyter notebook
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import confusion_matrix
%matplotlib inline 

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

In [ ]:
names = ['X_Minimum', 'X_Maximum', 'Y_Minimum', 'Y_Maximum', 'Pixels_Areas', 'X_Perimeter', 'Y_Perimeter', 'Sum_of_Luminosity', 'Minimum_of_Luminosity', 'Maximum_of_Luminosity', 'Length_of_Conveyer', 'TypeOfSteel_A300', 'TypeOfSteel_A400', 'Steel_Plate_Thickness', 'Edges_Index', 'Empty_Index', 'Square_Index', 'Outside_X_Index', 'Edges_X_Index', 'Edges_Y_Index', 'Outside_Global_Index', 'LogOfAreas', 'Log_X_Index', 'Log_Y_Index', 'Orientation_Index', 'Luminosity_Index', 'SigmoidOfAreas', 'Pastry', 'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults']

In [ ]:
df = pd.read_csv("steel.txt", sep = '\t', header=None, names = names)

In [ ]:

df.head()

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0         42         50     270900     270944           267           17   
1        645        651    2538079    2538108           108           10   
2        829        835    1553913    1553931            71            8   
3        853        860     369370     369415           176           13   
4       1289       1306     498078     498335          2409           60   

   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0           44              24220                     76   
1           30              11397                     84   
2           19               7972                     99   
3           45              18996                     99   
4          260             246930                     37   

   Maximum_of_Luminosity   ...    Edges_X_Index  Edges_Y_Index  \
0                    108   ...           0.4706         1.0000   
1                    123   ...           0.6000         0.9667   
2                    125   ...           0.7500         0.9474   
3                    126   ...           0.5385         1.0000   
4                    126   ...           0.2833         0.9885   

   Outside_Global_Index  LogOfAreas  Log_X_Index  Log_Y_Index  \
0                   1.0      2.4265       0.9031       1.6435   
1                   1.0      2.0334       0.7782       1.4624   
2                   1.0      1.8513       0.7782       1.2553   
3                   1.0      2.2455       0.8451       1.6532   
4                   1.0      3.3818       1.2305       2.4099   

   Orientation_Index  Luminosity_Index  SigmoidOfAreas   class  
0             0.8182           -0.2913          0.5822  Pastry  
1             0.7931           -0.1756          0.2984  Pastry  
2             0.6667           -0.1228          0.2150  Pastry  
3             0.8444           -0.1568          0.5212  Pastry  
4             0.9338           -0.1992          1.0000  Pastry  

[5 rows x 28 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1941 entries, 0 to 1940
Data columns (total 28 columns):
X_Minimum                1941 non-null int64
X_Maximum                1941 non-null int64
Y_Minimum                1941 non-null int64
Y_Maximum                1941 non-null int64
Pixels_Areas             1941 non-null int64
X_Perimeter              1941 non-null int64
Y_Perimeter              1941 non-null int64
Sum_of_Luminosity        1941 non-null int64
Minimum_of_Luminosity    1941 non-null int64
Maximum_of_Luminosity    1941 non-null int64
Length_of_Conveyer       1941 non-null int64
TypeOfSteel_A300         1941 non-null int64
TypeOfSteel_A400         1941 non-null int64
Steel_Plate_Thickness    1941 non-null int64
Edges_Index              1941 non-null float64
Empty_Index              1941 non-null float64
Square_Index             1941 non-null float64
Outside_X_Index          1941 non-null float64
Edges_X_Index            1941 non-null float64
Edges_Y_Index            194

In [ ]:
df.describe().T

count          mean           std        min  \
X_Minimum              1941.0  5.711360e+02  5.206907e+02     0.0000   
X_Maximum              1941.0  6.179645e+02  4.976274e+02     4.0000   
Y_Minimum              1941.0  1.650685e+06  1.774578e+06  6712.0000   
Y_Maximum              1941.0  1.650739e+06  1.774590e+06  6724.0000   
Pixels_Areas           1941.0  1.893878e+03  5.168460e+03     2.0000   
X_Perimeter            1941.0  1.118552e+02  3.012092e+02     2.0000   
Y_Perimeter            1941.0  8.296600e+01  4.264829e+02     1.0000   
Sum_of_Luminosity      1941.0  2.063121e+05  5.122936e+05   250.0000   
Minimum_of_Luminosity  1941.0  8.454869e+01  3.213428e+01     0.0000   
Maximum_of_Luminosity  1941.0  1.301937e+02  1.869099e+01    37.0000   
Length_of_Conveyer     1941.0  1.459160e+03  1.445778e+02  1227.0000   
TypeOfSteel_A300       1941.0  4.003091e-01  4.900872e-01     0.0000   
TypeOfSteel_A400       1941.0  5.996909e-01  4.900872e-01     0.0000   
Steel_Plate_Thickness  1941.0  7.873776e+01  5.508603e+01    40.0000   
Edges_Index            1941.0  3.317152e-01  2.997117e-01     0.0000   
Empty_Index            1941.0  4.142033e-01  1.372615e-01     0.0000   
Square_Index           1941.0  5.707671e-01  2.710584e-01     0.0083   
Outside_X_Index        1941.0  3.336110e-02  5.896117e-02     0.0015   
Edges_X_Index          1941.0  6.105286e-01  2.432769e-01     0.0144   
Edges_Y_Index          1941.0  8.134722e-01  2.342736e-01     0.0484   
Outside_Global_Index   1941.0  5.757342e-01  4.823520e-01     0.0000   
LogOfAreas             1941.0  2.492388e+00  7.889299e-01     0.3010   
Log_X_Index            1941.0  1.335686e+00  4.816116e-01     0.3010   
Log_Y_Index            1941.0  1.403271e+00  4.543452e-01     0.0000   
Orientation_Index      1941.0  8.328764e-02  5.008680e-01    -0.9910   
Luminosity_Index       1941.0 -1.313050e-01  1.487668e-01    -0.9989   
SigmoidOfAreas         1941.0  5.854205e-01  3.394518e-01     0.1190   

                               25%           50%           75%           max  
X_Minimum                  51.0000  4.350000e+02  1.053000e+03  1.705000e+03  
X_Maximum                 192.0000  4.670000e+02  1.072000e+03  1.713000e+03  
Y_Minimum              471253.0000  1.204128e+06  2.183073e+06  1.298766e+07  
Y_Maximum              471281.0000  1.204136e+06  2.183084e+06  1.298769e+07  
Pixels_Areas               84.0000  1.740000e+02  8.220000e+02  1.526550e+05  
X_Perimeter                15.0000  2.600000e+01  8.400000e+01  1.044900e+04  
Y_Perimeter                13.0000  2.500000e+01  8.300000e+01  1.815200e+04  
Sum_of_Luminosity        9522.0000  1.920200e+04  8.301100e+04  1.159141e+07  
Minimum_of_Luminosity      63.0000  9.000000e+01  1.060000e+02  2.030000e+02  
Maximum_of_Luminosity     124.0000  1.270000e+02  1.400000e+02  2.530000e+02  
Length_of_Conveyer       1358.0000  1.364000e+03  1.650000e+03  1.794000e+03  
TypeOfSteel_A300            0.0000  0.000000e+00  1.000000e+00  1.000000e+00  
TypeOfSteel_A400            0.0000  1.000000e+00  1.000000e+00  1.000000e+00  
Steel_Plate_Thickness      40.0000  7.000000e+01  8.000000e+01  3.000000e+02  
Edges_Index                 0.0604  2.273000e-01  5.738000e-01  9.952000e-01  
Empty_Index                 0.3158  4.121000e-01  5.016000e-01  9.439000e-01  
Square_Index                0.3613  5.556000e-01  8.182000e-01  1.000000e+00  
Outside_X_Index             0.0066  1.010000e-02  2.350000e-02  8.759000e-01  
Edges_X_Index               0.4118  6.364000e-01  8.000000e-01  1.000000e+00  
Edges_Y_Index               0.5968  9.474000e-01  1.000000e+00  1.000000e+00  
Outside_Global_Index        0.0000  1.000000e+00  1.000000e+00  1.000000e+00  
LogOfAreas                  1.9243  2.240600e+00  2.914900e+00  5.183700e+00  
Log_X_Index                 1.0000  1.176100e+00  1.518500e+00  3.074100e+00  
Log_Y_Index                 1.0792  1.322200e+00  1.732400e+00  4.258700e+00  
Orientation_Index          -0.33

In [ ]:
x = df[['X_Minimum', 'X_Maximum', 'Y_Minimum', 'Y_Maximum', 'Pixels_Areas',
       'X_Perimeter', 'Y_Perimeter', 'Sum_of_Luminosity',
       'Minimum_of_Luminosity', 'Maximum_of_Luminosity', 'Length_of_Conveyer',
       'TypeOfSteel_A300',  'Steel_Plate_Thickness',
       'Edges_Index', 'Empty_Index', 'Square_Index', 'Outside_X_Index',
       'Edges_X_Index', 'Edges_Y_Index', 'Outside_Global_Index', 'LogOfAreas',
       'Log_X_Index', 'Log_Y_Index', 'Orientation_Index', 'Luminosity_Index',
       'SigmoidOfAreas']]
y = df['class']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state =1, stratify = y)

In [ ]:
## Normalization

x_train = x_train.apply(zscore)
x_test = x_test.apply(zscore)

In [ ]:
x_train.describe()

X_Minimum     X_Maximum     Y_Minimum     Y_Maximum  Pixels_Areas  \
count  1.552000e+03  1.552000e+03  1.552000e+03  1.552000e+03  1.552000e+03   
mean  -5.880176e-17 -1.716840e-17  4.864379e-17  7.332336e-17 -1.355588e-17   
std    1.000322e+00  1.000322e+00  1.000322e+00  1.000322e+00  1.000322e+00   
min   -1.088906e+00 -1.224704e+00 -9.311520e-01 -9.311682e-01 -3.507202e-01   
25%   -9.919739e-01 -8.471459e-01 -6.741165e-01 -6.740999e-01 -3.358565e-01   
50%   -2.988334e-01 -3.042782e-01 -2.387872e-01 -2.388073e-01 -3.198918e-01   
75%    9.262181e-01  9.064596e-01  2.916699e-01  2.916719e-01 -2.046981e-01   
max    2.233102e+00  2.259037e+00  6.289125e+00  6.289059e+00  2.766149e+01   

        X_Perimeter   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
count  1.552000e+03  1.552000e+03       1.552000e+03           1.552000e+03   
mean  -3.038449e-17  5.356182e-18       1.466467e-18           1.442145e-16   
std    1.000322e+00  1.000322e+00       1.000322e+00           1.000322e+00   
min   -3.435531e-01 -1.763080e-01      -3.919739e-01          -2.647958e+00   
25%   -3.031699e-01 -1.509437e-01      -3.748848e-01          -6.587325e-01   
50%   -2.658932e-01 -1.255794e-01      -3.562236e-01           1.603605e-01   
75%   -9.504134e-02 -2.985317e-03      -2.425218e-01           6.908207e-01   
max    3.210898e+01  3.818931e+01       2.156229e+01           3.686361e+00   

       Maximum_of_Luminosity       ...        Outside_X_Index  Edges_X_Index  \
count           1.552000e+03       ...           1.552000e+03   1.552000e+03   
mean           -3.983068e-16       ...          -1.303367e-16  -5.708492e-17   
std             1.000322e+00       ...           1.000322e+00   1.000322e+00   
min            -5.026234e+00       ...          -5.669336e-01  -2.501633e+00   
25%            -3.379156e-01       ...          -4.770644e-01  -7.740283e-01   
50%            -1.762494e-01       ...          -4.136274e-01   1.035380e-01   
75%             5.243039e-01       ...          -1.757383e-01   7.750598e-01   
max             6.613729e+00       ...           1.034777e+01   1.609248e+00   

       Edges_Y_Index  Outside_Global_Index    LogOfAreas   Log_X_Index  \
count   1.552000e+03          1.552000e+03  1.552000e+03  1.552000e+03   
mean   -1.730431e-16          1.251862e-16  5.227777e-16 -3.436183e-16   
std     1.000322e+00          1.000322e+00  1.000322e+00  1.000322e+00   
min    -3.206979e+00         -1.160003e+00 -2.763171e+00 -2.150918e+00   
25%    -9.477897e-01         -1.160003e+00 -7.185383e-01 -7.057120e-01   
50%     5.731027e-01          9.022246e-01 -3.251793e-01 -3.416195e-01   
75%     8.076703e-01          9.022246e-01  5.232973e-01  3.931818e-01   
max     8.076703e-01          9.022246e-01  3.406614e+00  3.302201e+00   

        Log_Y_Index  Orientation_Index  Luminosity_Index  SigmoidOfAreas  
count  1.552000e+03       1.552000e+03      1.552000e+03    1.552000e+03  
mean   3.662591e-17       1.101639e-17      1.176035e-16    5.207747e-17  
std    1.000322e+00       1.000322e+00      1.000322e+00    1.000322e+00  
min   -3.061040e+00      -2.094173e+00     -5.895129e+00   -1.365812e+00  
25%   -6.920435e-01      -8.744709e-01     -4.251109e-01   -1.000863e+00  
50%   -1.586240e-01       3.297919e-02     -1.160030e-02   -2.548046e-01  
75%    7.418231e-01       8.580598e-01      4.455360e-01    1.222326e+00  
max    6.287410e+00       1.831643e+00      5.247249e+00    1.222914e+00  

[8 rows x 26 columns]

# 3. Principal Component Analysis

_By performing PCA, we are trying to reduce the number of Dimensions into a few less dimensions that are able to explain Variance in the actual dimensions_ 

__Splitting the Data into Train and Test with 30% data in the Test Set__

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 10, stratify =y)

x_train_std = x_train.apply(zscore)
x_test_std = x_test.apply(zscore)

## 3.3 Modelling and Classification

### 3.3.1 Logistic Regression

For Logistic Regression, an experimentation on HyperParameters 'penalty', 'C', 'tol' and 'solver' was performed. The following parameters attained the best accuracy. Results in the table below:

* **penalty** : l2(Outperforms l1)
* **C** : 5( Best amongst 0.01,0.1,0.5,0.9,1,5,10)
* **tol** : 1e-4(Best amongst 1e-4, 1e-3, 1e-2, 1e-1, 1, 1e2)
* **solver** : liblinear is the only algorithm that can be used with both 'l1' and 'l2'


In [ ]:
lm = LogisticRegression()
params = { 'penalty': ['l1','l2'],'C': [0.01,0.1,0.5,0.9,1,5,10], 'tol': [ 1e-4, 1e-3, 1e-2, 1e-1, 1, 1e2 ], 'solver': ['liblinear']}
GSLR = GridSearchCV(lm, params, cv=10)

In [ ]:
PCAmodelEval(GSLR)


Best Parameters : {'C': 5, 'penalty': 'l2', 'solver': 'liblinear', 'tol': 0.0001}

 [[ 26   1   6  56   8   2  22]
 [  6   0   0   1   8   2   0]
 [  6   0 101   1   1   8   0]
 [ 68   5  16  82  15   5  11]
 [ 10   3   0  17  10   3   4]
 [ 22   0   0   0   0   0   0]
 [ 28   0   2  27   0   0   0]]

Model Accuracy : 37.564
              precision    recall  f1-score   support

       Bumps       0.16      0.21      0.18       121
   Dirtiness       0.00      0.00      0.00        17
    K_Scatch       0.81      0.86      0.83       117
Other_Faults       0.45      0.41      0.42       202
      Pastry       0.24      0.21      0.22        47
      Stains       0.00      0.00      0.00        22
   Z_Scratch       0.00      0.00      0.00        57

 avg / total       0.37      0.38      0.37       583



### 3.3.2 K Nearest Neighbor

For KNN, an experimentation on parameters 'k', 'weights' and 'algorithm' was performed.The following parameters attained the best accuracy. Results in the table below:

* **k** : 7(Best amongst 1 to 59)
* **weights** : distance( Best amongst uniform and distance)
* **algorithm** : auto(Best amongst 'auto', 'ball_tree', 'kd_tree', 'brute')


In [ ]:
knn = KNeighborsClassifier()
k = np.arange(1, 60)
parameters = { 'n_neighbors': k, 'weights': ['uniform', 'distance'], 'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'] }
GSKnn = GridSearchCV(knn, parameters, cv=10)

In [ ]:
PCAmodelEval(GSKnn)


Best Parameters : {'algorithm': 'auto', 'n_neighbors': 7, 'weights': 'distance'}

 [[ 42   4   6  42   6   0  21]
 [  5   0   0   3   8   1   0]
 [  8   0  97  10   0   2   0]
 [ 59   0   9 100  15   2  17]
 [ 11   1   0  18  12   1   4]
 [  6   0   0  10   0   6   0]
 [ 18   0   2  24   2   1  10]]

Model Accuracy : 45.798
              precision    recall  f1-score   support

       Bumps       0.28      0.35      0.31       121
   Dirtiness       0.00      0.00      0.00        17
    K_Scatch       0.85      0.83      0.84       117
Other_Faults       0.48      0.50      0.49       202
      Pastry       0.28      0.26      0.27        47
      Stains       0.46      0.27      0.34        22
   Z_Scratch       0.19      0.18      0.18        57

 avg / total       0.46      0.46      0.45       583



In [ ]:
nb = GaussianNB()
nb.fit(x_train_reduced, y_train)
y_test_naive = nb.predict(x_test_reduced)
print(confusion_matrix(y_test, y_test_naive))
print("\n\n The Accuracy is :",round(nb.score(x_test_reduced, y_test)*100,2))
print(metrics.classification_report(y_test, y_test_naive))


[[ 49   3   1  50   4   0  14]
 [  6   0   0   2   9   0   0]
 [  3   0 102  12   0   0   0]
 [ 70   5   4  96  16   0  11]
 [  9   0   3  28   4   0   3]
 [ 11   0   2   9   0   0   0]
 [ 13   0   1  40   1   0   2]]


 The Accuracy is : 43.4
              precision    recall  f1-score   support

       Bumps       0.30      0.40      0.35       121
   Dirtiness       0.00      0.00      0.00        17
    K_Scatch       0.90      0.87      0.89       117
Other_Faults       0.41      0.48      0.44       202
      Pastry       0.12      0.09      0.10        47
      Stains       0.00      0.00      0.00        22
   Z_Scratch       0.07      0.04      0.05        57

 avg / total       0.40      0.43      0.41       583

